### PR TITLE
Add notify function to GCDQueue

### PR DESCRIPTION
**Pull request by dourgulf**

### CODE REVIEW

**Comment by mjmsmith** [comment]
@dourgulf The GCDQueue method queueNotifyBlock:inGroup: currently does the same thing. Just curious if the PR is because (1) you hadn't seen it, or (2) you think it would be more appropriate as a method on GCDGroup instead. Thx!

**Comment by dourgulf** [comment]
@mjmsmith Oh, I hadn't seen it:). Cancel this PR~

**Comment by mjmsmith** [comment]
@dourgulf no problem, I think it actually makes more sense as a member on GCDGroup than GCDQueue, which is probably why it was easy to miss. I'll add it in the next update.

**Comment by dourgulf** [comment]
Nice:)

**Pull request closed without merging**
